### ISSUE TITLE
gpg, gpgconf, gpgsm zombie processes after each conversation

### ISSUE THREAD

**Issue by ilkoss** [jodconverter/jodconverter#412]
Hi,
I'm using the jodconverter-local-lo  (last version) in Spring Boot with LibreOffice 24.2.6.2 420(Build:2) after each conversation there a lot of zombie GPG - procceses in the memory. 

**- I'm using the Spring Boot Starter - Hier my config:**

```
jodconverter:
  local:
    enabled: true
    portNumbers: 2003, 2004
    existing-process-action: kill
    keep-alive-on-shutdown: false
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages

      xhtml:
        store:
          TEXT:
            FilterOptions: EmbedImages
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
```

Hier the code for the Conversation:

```
    //Autowiring
    DocumentConverter converter;

    public ByteArrayOutputStream convertToPfdStream(final InputStream doc) {
        try (var os = new ByteArrayOutputStream()) {
            converter.convert(doc).as(DOCX).to(os).as(PDF).execute();
            return os;
        } catch (IOException | OfficeException e) {
            log.info("Exception caught!: ", e);
        }
    }
```

**Hier the top output:**

```
Tasks:  36 total,   1 running,   4 sleeping,   0 stopped,  31 zombie
%Cpu(s):  1.3 us,  0.9 sy,  0.0 ni, 97.2 id,  0.0 wa,  0.0 hi,  0.7 si,  0.0 st 
MiB Mem :  32091.9 total,   2329.9 free,   8639.9 used,  21926.6 buff/cache     
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  23452.0 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                 
      1 kvbapp    10 -10 6554.7m 841.1m  26.4m S   1.0   2.6   3:07.85 java                                                                    
   4894 kvbapp    10 -10  830.0m 203.3m 113.7m S   0.0   0.6   0:06.23 soffice.bin                                                             
   4873 kvbapp    10 -10  827.3m 194.2m 113.3m S   0.0   0.6   0:06.14 soffice.bin                                                             
   5984 kvbapp    10 -10   11.5m   5.5m   3.4m R   0.0   0.0   0:00.01 top                                                                     
    742 kvbapp    10 -10    7.4m   4.4m   3.8m S   0.0   0.0   0:00.01 bash                                                                    
    191 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgconf                                                                 
    193 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgconf                                                                 
    195 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpg                                                                     
    197 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgsm                                                                   
    199 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgconf                                                                 
    212 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgconf                                                                 
    214 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgconf                                                                 
    216 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpg                                                                     
    218 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgsm                                                                   
    220 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgconf                                                                 
   2541 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgconf                                                                 
   2543 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgconf                                                                 
   2545 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpg                                                                     
   2547 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgsm                                                                   
   2549 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgconf                                                                 
   2561 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgconf                                                                 
   2563 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgconf                                                                 
   2565 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpg                                                                     
   2567 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgsm                                                                   
   2569 kvbapp    10 -10    0.0m   0.0m   0.0m Z   0.0   0.0   0:00.00 gpgconf 
```

**Comment by vasek00786** [comment]
Hi!
I catch similar problem - after JodConverter restarts OO (after 200 tasks) there is a new zombie process in system. I fround than problem in class LocalOfficeProcessManager, method detectOfficeDescriptor . In 691 line we start process, which became zombie. 
Also, it seems strange: why do we need to detect office descriptor after during restart OO? Does OO can change version while we restart it process? 

<img width="583" alt="Image" src="https://github.com/user-attachments/assets/fdf337f2-f712-4876-8144-4552043a6913" />

**Comment by sbraconnier** [comment]
It seems to be related to [this] (https://bugs.documentfoundation.org/show_bug.cgi?id=117523)

@ilkoss @vasek00786 Could you please trye with the jodconverter 4.4.9-SNAPSHOT version using the sonatype snapshot repo:

https://oss.sonatype.org/content/repositories/snapshots

**Comment by sbraconnier** [comment]
I'll close this one since it seems to have been fixed (no comeback). Feel free to re-open if needed.

**Comment by vasek00786** [comment]
Hi! sorry, i'm late. I tried with version 4.4.11 but the issue is still active: there are new zombie processes after jodconverter restart OO

<img width="1533" height="729" alt="Image" src="https://github.com/user-attachments/assets/c5518218-0e41-40cc-a5c6-2411bf6fd86c" />
P.S. i don't have persmissions to reopen issue

**Comment by sbraconnier** [comment]
@vasek00786 `detectOfficeDescriptor` doesn't start a process anymore so it's probably the main one that stays alive. I'll look into it.

**Comment by sbraconnier** [comment]
@vasek00786 This seems to be a known LibreOffice issue with LibreOffice running in a container. Could you try what is suggested in this issue as workaround and let me known if it helps?

https://bugs.documentfoundation.org/show_bug.cgi?id=142772
